# Generated by Django 5.0.6 on 2024-05-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='total_seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='busseat',
            name='seat_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='available_seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='price',
            field=models.IntegerField(),
        ),
    ]
