# Generated by Django 5.0.6 on 2024-05-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_bus_total_seats_alter_busseat_seat_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number_phone',
            field=models.CharField(default='Empty', max_length=11),
        ),
    ]
