# Generated by Django 5.0.6 on 2024-05-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_number_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='destination_address',
            field=models.CharField(default='Empty', max_length=50),
        ),
        migrations.AddField(
            model_name='route',
            name='origin_address',
            field=models.CharField(default='Empty', max_length=50),
        ),
    ]
