# Generated by Django 5.0.6 on 2024-05-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
