# Generated by Django 5.0.6 on 2024-05-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_profile_email_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='number_phone',
        ),
    ]
