# Generated by Django 5.0.6 on 2024-05-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_profile_first_name_remove_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='snils',
            field=models.CharField(default='Empty', max_length=11),
        ),
    ]
