# Generated by Django 5.0.6 on 2024-05-15 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_profile_snils'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='seats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.busseat'),
        ),
    ]
