# Generated by Django 5.0.6 on 2024-05-15 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_schedule_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='seats',
        ),
        migrations.AddField(
            model_name='busseat',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.schedule'),
        ),
    ]
